# Generated by Django 5.2.6 on 2026-04-13 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0004_alter_prestamo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, help_text='Calculado automáticamente: cantidad × precio_unitario', max_digits=14)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_operacion', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Detalle de operación',
                'verbose_name_plural': 'Detalles de operación',
                'db_table': 'detalle_operacion',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField(auto_now_add=True)),
                ('cantidad_devuelta', models.PositiveIntegerField()),
                ('estado_devolucion', models.CharField(choices=[('bueno', 'Buen estado'), ('dañado', 'Dañado'), ('perdido', 'Perdido')], default='bueno', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('detalle', models.OneToOneField(help_text='Detalle del préstamo que se devuelve.', on_delete=django.db.models.deletion.PROTECT, related_name='devolucion', to='operaciones.detalleoperacion')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'db_table': 'devolucion',
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_operacion', models.CharField(blank=True, help_text='Auto-generado: VEN-0001 o PRE-0001', max_length=20, unique=True)),
                ('tipo_operacion', models.CharField(choices=[('venta', 'Venta'), ('prestamo', 'Préstamo')], max_length=10)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='activa', max_length=12)),
                ('cliente', models.CharField(blank=True, help_text='Nombre del cliente externo (opcional).', max_length=150, null=True)),
                ('fecha_operacion', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField(blank=True, help_text='Solo aplica para préstamos.', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario del sistema que registra la operación.', on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'db_table': 'operacion',
                'ordering': ['-fecha_operacion', '-id'],
            },
        ),
        migrations.AddField(
            model_name='detalleoperacion',
            name='operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operaciones.operacion'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleoperacion',
            unique_together={('operacion', 'producto')},
        ),
    ]
