# Generated by Django 5.2.6 on 2026-04-13 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_prestamo_options_and_more'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.ForeignKey(db_column='productos_marca_marca_id', on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_prestamo_productos', to='inventario.marca')),
                ('prestamo', models.ForeignKey(db_column='productos_prestamo_pres_ID', on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_prestamo_productos', to='inventario.prestamo')),
                ('producto', models.ForeignKey(db_column='productos_prod_id', on_delete=django.db.models.deletion.CASCADE, related_name='operaciones_prestamo_productos', to='inventario.producto')),
                ('tipo_categoria', models.ForeignKey(db_column='productos_tipo_categoria_tipr_id', on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_prestamo_productos', to='inventario.tipocategoria')),
            ],
            options={
                'verbose_name': 'Relación Préstamo-Producto',
                'verbose_name_plural': 'Relaciones Préstamo-Producto',
                'db_table': 'Operaciones_has_productos',
                'unique_together': {('prestamo', 'producto')},
            },
        ),
    ]
