# Generated by Django 5.2.6 on 2026-04-13 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_prestamoproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrestamoProducto',
        ),
    ]
