# Generated by Django 5.2.6 on 2026-04-13 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_delete_prestamoproducto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucion',
            options={'ordering': ['-fecha_devolucion', '-id'], 'verbose_name': 'Devolución', 'verbose_name_plural': 'Devoluciones'},
        ),
        migrations.AddField(
            model_name='detalleoperacion',
            name='cantidad_devuelta',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Acumulado de unidades devueltas sobre este detalle.'),
        ),
        migrations.AlterField(
            model_name='detalleoperacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='operaciones.detalleoperacion'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='cliente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='codigo_operacion',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
