# Generated by Django 5.2.6 on 2026-07-01 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_alter_devolucion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='operacion',
            index=models.Index(fields=['estado'], name='operacion_estado_f60edf_idx'),
        ),
        migrations.AddIndex(
            model_name='operacion',
            index=models.Index(fields=['tipo_operacion', 'estado'], name='operacion_tipo_op_ffcd5a_idx'),
        ),
        migrations.AddIndex(
            model_name='operacion',
            index=models.Index(fields=['fecha_devolucion'], name='operacion_fecha_d_75c028_idx'),
        ),
    ]
