# Generated by Django 5.2.6 on 2026-04-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(blank=True, help_text='Se genera automáticamente si se deja vacío (ej: ELE-APL-001)', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_cantidad_disponible',
            field=models.IntegerField(default=0, help_text='Unidades disponibles actualmente'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_cantidad_prestada',
            field=models.IntegerField(default=0, help_text='Unidades actualmente prestadas'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_cantidad_total',
            field=models.IntegerField(default=0, editable=False, help_text='Calculado automáticamente: disponible + prestada'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado'), ('Mantenimiento', 'Mantenimiento'), ('Dañado', 'Dañado')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_foto',
            field=models.ImageField(blank=True, help_text='Imagen del producto (jpg, png, webp…)', null=True, upload_to='productos/fotos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_valor_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Valor unitario del producto', max_digits=12),
        ),
    ]
