# Generated by Django 5.2.6 on 2026-04-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_codigo_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo_prestamos',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del producto (opcional).', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(blank=True, help_text='Nombre del proveedor (opcional).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(blank=True, help_text='Se genera automáticamente: CAT-MAR-001. Déjalo vacío.', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_cantidad_disponible',
            field=models.IntegerField(default=0, help_text='Unidades disponibles actualmente.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_cantidad_prestada',
            field=models.IntegerField(default=0, editable=False, help_text='Calculado automáticamente según préstamos activos.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_cantidad_total',
            field=models.IntegerField(default=0, editable=False, help_text='Calculado automáticamente: disponible + prestada.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado'), ('Mantenimiento', 'Mantenimiento'), ('Dañado', 'Dañado'), ('Agotado', 'Agotado')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_foto',
            field=models.ImageField(blank=True, help_text='Foto del producto (jpg, png, webp…).', null=True, upload_to='productos/fotos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_valor_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Valor unitario del producto.', max_digits=12),
        ),
    ]
