# Generated by Django 5.2.6 on 2026-04-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_producto_tipo_prestamos_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'verbose_name': 'Tipo de préstamo', 'verbose_name_plural': 'Tipos de préstamo'},
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_operacion_permitida',
            field=models.CharField(choices=[('venta', 'Solo venta'), ('prestamo', 'Solo préstamo'), ('mixto', 'Venta y préstamo')], default='mixto', help_text='Define si el producto se vende, se presta o ambos.', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(blank=True, help_text='Auto-generado: CAT-MAR-001', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_cantidad_prestada',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_cantidad_total',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_foto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/fotos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='prod_valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
