# Generated by Django 5.2.6 on 2026-04-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_prestamo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='prod_cantidad_en_mantenimiento',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
