# Generated by Django 5.2.6 on 2026-06-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto_prod_cantidad_en_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='prod_stock_minimo',
            field=models.IntegerField(default=0, help_text='Umbral mínimo. Si el disponible cae a este nivel o menos, se considera stock bajo.'),
        ),
    ]
