# Generated by Django 5.2.6 on 2026-07-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_producto_prod_stock_minimo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['prod_estado'], name='productos_prod_es_a650e5_idx'),
        ),
    ]
