# Generated by Django 5.2.6 on 2026-04-13 04:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['-fecha_ingreso', '-mant_id'], 'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='mant_fecha',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='cantidad_baja',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Unidades que no se pudieron recuperar (pérdida total).'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='cantidad_ingresada',
            field=models.PositiveIntegerField(default=0, help_text='Unidades que ingresan a mantenimiento.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='cantidad_recuperada',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Unidades que salieron reparadas (se registra al finalizar).'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=12),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_salida',
            field=models.DateField(blank=True, help_text='Se llena automáticamente al finalizar.', null=True),
        ),
        migrations.AlterField(
            model_name='costo',
            name='cost_fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='costo',
            name='cost_partes_afectadas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='costo',
            name='cost_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo total del mantenimiento.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='costo',
            field=models.ForeignKey(blank=True, db_column='costo_cost_id', help_text='Se puede asignar el costo al finalizar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='mantenimiento.costo'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='mant_descripcion',
            field=models.TextField(blank=True, help_text='Descripción del daño o motivo de ingreso.', null=True),
        ),
        migrations.CreateModel(
            name='SalidaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField(auto_now_add=True)),
                ('cantidad_recuperada', models.PositiveIntegerField(help_text='Unidades reparadas que vuelven al stock.')),
                ('cantidad_baja', models.PositiveIntegerField(default=0, help_text='Unidades que no se pudieron reparar (pérdida total).')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('costo', models.ForeignKey(blank=True, help_text='Costo final de la reparación (opcional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='mantenimiento.costo')),
                ('mantenimiento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='salida', to='mantenimiento.mantenimiento')),
            ],
            options={
                'verbose_name': 'Salida de mantenimiento',
                'verbose_name_plural': 'Salidas de mantenimiento',
                'db_table': 'salida_mantenimiento',
            },
        ),
    ]
