# Generated by Django 5.2.6 on 2026-07-01 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_producto_productos_prod_es_a650e5_idx'),
        ('mantenimiento', '0002_alter_mantenimiento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['estado'], name='mantenimien_estado_8086b3_idx'),
        ),
    ]
